blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/yani-/wp-contributor-sponsors/blob/main/SECURITY.md
    about: Please report security issues privately. See SECURITY.md.
